"""add new columns to users and jobs

Revision ID: 0458e7c2ed80
Revises: 54ed31ccf1fd
Create Date: 2026-02-07 20:16:36.935592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0458e7c2ed80'
down_revision = '54ed31ccf1fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('created_at')
        batch_op.drop_column('company_name')
        batch_op.drop_column('full_name')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('job_type')

    # ### end Alembic commands ###
