"""empty message

Revision ID: 451eb97c1ca2
Revises: b52b47e74f33
Create Date: 2026-02-09 20:45:45.742279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451eb97c1ca2'
down_revision = 'b52b47e74f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index('ix_users_email', ['email'], unique=1)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
