"""empty message

Revision ID: 722474687c1a
Revises: eaa529575d34
Create Date: 2026-02-09 19:14:42.456738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722474687c1a'
down_revision = 'eaa529575d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index('ix_users_email', ['email'], unique=1)

    # ### end Alembic commands ###
