"""empty message

Revision ID: 730552bcafaa
Revises: 3d44aed6cc51
Create Date: 2026-02-09 14:06:27.612802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730552bcafaa'
down_revision = '3d44aed6cc51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index('ix_users_email', ['email'], unique=1)

    # ### end Alembic commands ###
